language: php

php:
  - 5.3
  - 5.4

env:
  - DB=mysql CAKE_VERSION=2.3.10
  - DB=mysql CAKE_VERSION=master
  - DB=mysql CAKE_VERSION=2.5

matrix:
  include:
    - php: 5.4
      env:
        - PHPCS=1

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../datasources plugins/datasources
  - chmod -R 777 ../cakephp/app/tmp
  - sh -c "if [ '$PHPCS' = '1' ]; then pear channel-discover pear.cakephp.org; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then pear install --alldeps cakephp/CakePHP_CodeSniffer; fi"
  - phpenv rehash
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'travis',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => ''
    );
    }" > ../cakephp/app/Config/database.php

script:
  - sh -c "if [ '$PHPCS' = '1' ]; then phpcs -p --extensions=php --standard=CakePHP ./plugins/datasources; else ./lib/Cake/Console/cake test Datasources AllDatasources --stderr; fi"

notifications:
  email: false
